### ISSUE TITLE
Sequence with one-letter codes?

### ISSUE THREAD

**Issue by davidarndt** [NMRExchangeFormat/NEF#13]
Sometimes people may want to get the sequence of one or more chains from a NEF file. In NMR-STAR 2.1 and 3.1 formats, this is easy since one just finds _Mol_residue_sequence or _Entity.Polymer_seq_one_letter_code, respectively (or one can visually inspect the file without having to remember these labels). But in the NEF examples, there is no such field. Will a PDB ID or other external ID always be present that would be used to easily get a FASTA file? If not, to get the sequence (in a format using one-letter codes), one would need to either write a script or use text manipulation tricks and use something like the Three to One form at http://bioinformatics.org/sms2/three_to_one.html. Not everyone will have the expertise for this, or think of the right tricks to use. Should perhaps the sequence(s) of chains be written out in NEF files using one-letter codes?

**Comment by rhfogh** [comment]
That is for the community to decide. My personal opinion would be not to add one-letter-code sequences, in the interest of keeping the format as short and simple as possible, and of avoiding storing redundant information that must then be kept consistent.

What do people think?

**Comment by agutmanas** [comment]
I would second the opinion that including one-letter sequences may lead to inconsistencies. Instead, as suggested by Geerten sitting next to me, it would be better to have a set of tools, which can perform such tasks, e.g. NEF2FASTA translation.
Also, for publicly released structures, I would expect that PDB and BMRB IDs would be included and the tags for related database entries are already available.
