### ISSUE TITLE
Validation and atom nomenclature

### ISSUE THREAD

**Issue by rhfogh** [NMRExchangeFormat/NEF#35]
Validation and atom nomenclature are really two different things.

The rule that an atom indicator must contain chain code, sequence code, atom name and (optionally empty) residue type is a matter of validity, as is the rule that a given chain code and sequence code must be paired with the same residue type throughout the file,, or the rule that identifiers that differ only by case are not allowed (e.g. HA and Ha). Break those and the file is invalid.

An atom name like "?@295-1" is perfectly valid, on the  other hand. It cannot (or course) be converted into a IUPAC atom name, no matter what the context, but the format rules say that names that cannot be so mapped are allowed, and are treated as anonymous asignment names. 

As I understand the system, the actual atoms present follow from the sequence description, through the residue types ('three letter codes'). Atom names are matched to these, using three different types of wildcards:
'%' : "a sequence of digits" or "[0-9]+"
'*' : "any string" or ".*"
'X' and 'Y', which signify one of two alternative branches (but we do not know which one) for atoms and groups with ambiguity codes 2 or 3. 

So, there are two thing to say about 'valid atom names':
1) it is a matter not so much of valid NEF files, but of what names other programs can interpret - so maybe the best place to put it is in a file reader - e.g. a BMRB one.
2) I do not think you can decide what is interpretable without comparing it to a known set of templates with known atom names.  Whether e.g. 'HB%' can be interpreted (and how) depends on whether the relevant residue is ALA, GLU, THR, GLY - or DNA.

**Comment by kumar-physics** [comment]
I don't expect to see atom names like "?@295-1" in a final NEF file ready for deposition at wwPDB. Moreover as an exchange format, how does other software will interpret "?@295-1". You may say, other software are not necessarily parse and understand these data. Then what do they exchange between softwares?

**Comment by kumar-physics** [comment]
To resolve the issues with "%","X" and "Y", why don't you provide a mapping table for all atoms in the 20 amino acids?. I hope that will solve the issue.

**Comment by kumar-physics** [comment]
Let me explain what I mean by validation. I want to make sure the NEF wildcards "%", "X" and "Y" are used according to NEF rules. How can I check/validate that? Can all these wildcards can be interchangeably used?

**Comment by rhfogh** [comment]
There are at least two cases for using atom names that can not be matched to a structure.

One is to hold information during the assignment process. This information should be kept a) when a program uses NEF for storage or transfers between projects, b) for transfer between different assignment programs, e.g. Sparky and CcpNmr.

The other is to deal with incomplete assignments, minor conformations, and unknown impurities. Listing what resonances can be found in the spectra (and might therefore give rise to peaks) is potentially useful information - it might avoid using known impurity peaks to generate a structure.

Now a program - or a deposition system - does not have any obligation to make use of anonymous assignments. But it should be prepared to deal with files that contain them (e.g. by skipping uninterpretable atoms and printing an error message). Whether the BMRB wishes to store observed but incompletely assigned chemical shifts is for the BMRB to decide.

As for how the data should be interpreted, the rules are at least precise: The atom names are matched against the IUPAC names of the target system using the (precisely defined) rules for wildcards. Atom names that match can be mapped. Atom names that do not match are treated as anonymous.
