### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by rhfogh** [NMRExchangeFormat/NEF#36]
We need more test data, from more varied sources, with more varied contents (complexes, multimers, nucleic acids, unusual topologies, assigned peak lists, ...).

For now I shall finish adding the ten CASD_NMR 2013 projects. With the conversion code I had to write to make those I should be able to make a test file from any DOCR project without too much hassle. So if anyone has a good suggestion for a test project, I can take a look. Meanwhile I shall see if I can convert at least one of the dimers in Guys X-ray/NMR data set.

Looking forward to seeing more data...

**Comment by kumar-physics** [comment]
It wold be helpful to provide the original files from(in their software specific form) CASD_NMR project.  Looking for more examples with ligands and nucleic acids.

**Comment by rhfogh** [comment]
I have added download links to the CASD_NMR README file.

**Comment by rhfogh** [comment]
I have read the XLPOR-NIH file (in the CCPN NEF reader) and have some comments (see attached file).

[XplorNIH-simple-comments.txt](https://github.com/NMRExchangeFormat/NEF/files/415306/XplorNIH-simple-comments.txt)
