### ISSUE TITLE
Degenerate checmical shifts

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#55]
How degenerate chemical shifts are handled in NEF? Are they treated as ambiguous chemical shifts or uniquely assigned chemical shifts?. I see both representation in the same example file 

> A  372  TYR  HD1   7.239    0.02
> A  372   TYR  HD2   7.239    0.02

and 

> A  375  HIS  HBX   3.037    0.02
> A  375  HIS  HBY   3.037    0.02

Is there any rule for these cases?

**Comment by rhfogh** [comment]
Both versions are allowed. 

If you know from the start that the shifts are degenerate I would recommend using the (uniquely assigned) IUPAC names, e.g. for fast-rotating aromatic rings (if I am not mistaken the example with A 372 TYR was converted from a BMRB file and that was how the names came out - I suspect that the relevant protons did not have ambiguity code 3 set in the original). If, on the other hand you assign one methylene proton to HBX and later decide that HBY is at the same shift, I would not require the user to change his assignments.
