### ISSUE TITLE
CSROSETTA peak list problem

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#58]
CSROSETTA example file contains 4D peak list, but in the loop only 3 chemical shift values are provided. Is it an error or is it a reduced dimentionality experiment ?.

**Comment by rhfogh** [comment]
I would say it is an error. The spectrum dimensions must match the peaklist dimensions. If you had a hC_CH.NOESY - a 3D version of a 4D experiment where you do not measure the frequency of the first proton - you should describe it as a 3D spectrum with an indirect NOESY transfer. I guess we should hear from the depositors what situation they are trying to describe.

**Comment by AlisonBarrett** [comment]
4D. I will fix this, thank you.
