### ISSUE TITLE
Test data and mmCIF

### ISSUE THREAD

**Issue by rhfogh** [NMRExchangeFormat/NEF#72]
When version 1.0 is frozen we shall need everybody (please?) to resubmit existing test data and and more to represent your program output. For a complete test, any program that exports structures should give an mmCIF file with the structures in addition to the .nef file. The mmCIF file contains the author-to-IUPAC name mapping, and is necessary for testing for the RCSB, BMRB, and others who make use of structures together with the NMR data.

**Comment by kumar-physics** [comment]
I agree with Rasmus and it is critical that software generated test data set consists of NEF file and associated structure in mmCIF file. I am also requesting the software developers to provide the test data set as soon as possible. Thanks

**Comment by dacase** [comment]
I wonder if we are not trying to require more from version 1.0 than is reasonable.  I'm guessing(?) that most NMR refinement programs are still very much wedded to PDB-format files; if they do support mmCIF, it is not likely to include the author-to-IUPAC name mapping fields that are desired here.  We might want to consider allowing the test data to consist of PDB-format files plus NEF files.

**Comment by kumar-physics** [comment]
I think this is the right time to change and move forward. PDB-format has already been outdated by wwPDB. I encourage NMR software community to take this as an opportunity to bring the change and give support to mmCIF format.  I know PDB format is the backbone for most of the NMR software and its very difficult to reprogram everything, but at the same time I see this as a positive change, which enables us to easily exchange data with other structure determination communities like X-Ray and EM.
