### ISSUE TITLE
Multiline comments in example file

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#81]
Our STAR parser produced and error while reading  [Commented_Example.nef](https://github.com/NMRExchangeFormat/NEF/blob/master/specification/Commented_Example.nef) .
The following method is not allowed
> ; Optional item
> For comments.
> Any multiline text can be put here
> ;

The correct format according to original STAR specification  should be like this

> ;
> Optional item
> For comments.
> Any multiline text can be put here
> ;

Please correct it.

**Comment by elulrich** [comment]
Hi,

Shouldn't the format be like this:

; Optional item For comments. Any multiline text can be put here
;

Thanks,
Eldon

**Comment by jonwedell** [comment]
Eldon,

I'm wondering if your e-mail client changed the newlines in your text. My understanding was that the multiline comments must start and end with a semi-colon on its own line. From [the specification](http://pubs.acs.org/doi/pdf/10.1021/ci00019a005):

(d) a sequence of lines starting with, and finishing with, a
semicoloncharacter <;> (ASCII 59) as the first character
of a line

The issue with the line in the file is that the first line of the multi-line comment does not start and end with a semicolon, it only starts with one.

Regards,
Jon

**Comment by jonwedell** [comment]
Hmm. The specification states:

(d) a sequence of lines starting with, and finishing with, a
semicoloncharacter <;> (ASCII 59) as the first character
of a line.

I interpreted this to mean that the first and last line start and end with (only contain) a newline, but I think that Eldon is correct in that the line must only start with a semi-colon.

**Comment by elulrich** [comment]
Hi,

The definition that we have used and I believe there is an example in 
the specification files is this:

; some text
some more text
some more text
;


The text is bracketed by semicolons that start the first line and then 
close the text by being on the first character on the last line.

Eldon

**Comment by kumar-physics** [comment]
Okey then Commented_Example.nef is fine and I close this issue. We will fix our parser.
