### ISSUE TITLE
Software specific tag in nmr_meta_data saveframe

### ISSUE THREAD

**Issue by kumar-physics** [NMRExchangeFormat/NEF#82]
Commented_Example.nef file contains a software specific tag in the nmr_meta_data saveframe

```
# program-specific parameter
_nef_program_script.cyana_parameter_1
```
It is defined as loop a loop tag along with other tags(program_name,script_name,script). Consider a situation with more than one program is used(example: CYANA and XPLOR) Now cyana_parameter_1 column become meaningless for a row containing  XPLOR data.  

"cyana_parameter_1" is a software specific tag, which should go into software specific saveframe.  

Thanks

**Comment by rhfogh** [comment]
According to specifications/Overview.md, section 4, "Program-specific namespaces", program-specific tags are allowed both as saveframes, loop columns, and individual tags within standard saveframes. So as things stand, programs must be prepared for this kind of situation. As always, alternative solutions can be proposed as change requests.
