### ISSUE TITLE
Should we not use OXT/HXT for C-terminal carboxylates in proteins?

### ISSUE THREAD

**Issue by dacase** [NMRExchangeFormat/NEF#87]
Generally, the wwPDB uses atom names that match IUPAC recommendations, at least as I understand it.  Based on recent updates, it appears that the wwPDB nomenclature of OXT/HXT for a C-terminal carboxylate is an exception to this general rule.

Our software (Amber) is used for many tasks, not just NMR refinement, and it is universal to follow the wwPDB standard with regards to these names.  My view is that the wwPDB conventions should take precedence over any IUPAC rules that conflict with them, since the main point of the NEF standard is to have useful restraint files that can be used in conjunction with coordinate files from the wwPDB.

In this particular case, it doesn't make much difference, since assignments and restraints for these two nuclei are quite rare.  But this issue also arises elsewhere, e.g. for hydroxy-proline: here the wwPDB hydrogen names are inconsistent with proline itself.  Still, the wwPDB standard is widely used and easy to find; I'm not sure how I would determine the correct "IUPAC" names for a modified amino acid or a ligand.  So my vote would be in favor of the wwPDB names, as codified in its "components" library.  Otherwise, all our software needs to (a) be able to figure out what the IUPAC names are, and (b) maintain a mapping between those names and the wwPDB names (since users will expect PDB formatted files to adhere to the wwPDB conventions.)

[In cases where there is no wwPDB standard, then IUPAC rules would seem to make the most sense.]

**Comment by elulrich** [comment]
Hi,

I have not yet been able to find the published allowed exception, but I 
seem to remember the PDB requesting that OXT/HXT be allowed as IUPAC 
names after the publication of the recommendations and the authors of 
the IUPAC recommendations agreeing to this exception.

Eldon

**Comment by elulrich** [comment]
Hi,

I have not yet been able to find the actual addendum to the IUPAC 
recommendations, but did find this statement in slides presented to the 
2007 wwpdb advisory board:

All discrepancies have been resolved in the remediated files, with the 
minor exception of atoms at the C-terminus
IUPAC-IUBMB-IUPAB                   wwPDB
             H''                                         HXT
             O'                                          O
             O''                                         OXT
Since these atoms are not observed by NMR spectroscopists, we do not 
consider this to be a problem
We plan to write an addendum to the IUPAC-IUBMB-IUPAB “Recommendations” 
for submission to Pure & Appl. Chem. to formalize these as “accepted 
atom designators”


Also, I would agree with David that the use of atom nomenclature from 
the wwPDB chemical compound library is best. If this is not followed, 
the wwPDB will change the atom nomenclature in the coordinates, but not 
in the restraints files. This can cause problems.

Best regards,
Eldon

**Comment by rhfogh** [comment]
Hi,

We have been thinking about this. Using the wwPDB nomenclature would be clear and well-defined, and we would be doing that anyway for anything that had a PDB compound ID. By and large I agree with David
that " the wwPDB conventions should take precedence over any IUPAC rules that conflict with them", and that we should IUPAC for anything not in the wwPDB.

- The main point remaining is that this time I want to be sure that the consensus is indeed for changing the current specification. I am sending some individual nagging letters, but could anyone reading this please make their opinion (or indifference) known?

- If I make this change (and at this point it is a change) presumably the format identifier should be increased to 1.1. Does this cause problems for anyone?

- Can anybody say anything about differences between IUPAC and wwPDB, apart from the three atoms mentioned? I do not quite follow Davids PRO/HYP example: when I look in https://files.rcsb.org/ligands I find that PRO has the protons HG2,HG3,HD2,HD3, whereas HYP has the protons HG,HG1,HD22,HD23, which are different also for the wwPDB. I have come across examples that are (hopefully) non-IUPAC, like the methyl group in 6MZ where the protons are named H9, H9C1, H9C2, but any relevant information would be welcome.

**Comment by elulrich** [comment]
Hi,

I believe the wwPDB has accepted the IUPAC recommended nomenclature for 
the standard amino acid and nucleic acid residues (HB2 and HB3 - IUPAC 
versus HB1 and HB2 - old PDB). The exception, which I believe was 
approved, is the use of OXT/HXT. The wwPDB claims to use IUPAC atom 
nomenclature for other residues and ligands as defined in other IUPAC 
documents. In any case, I would vote for following the atom nomenclature 
found in the wwPDB ligand library for non-standard residues and ligands 
whenever possible.

The problem will be that software users will invent their own 
nomenclature for non-standard residues and ligands even if they exist in 
the ligand library. I am not sure how the software developers can 
control this or can even be asked to control this. The wwPDB has the 
tools for identifying these situations and converting the atom 
nomenclature in the atomic coordinate files to that found in the ligand 
library.

For non-standard residues and ligands not in the current library, the 
user can do anything. But, I believe, the wwPDB will look at the 
structure attempt to create an IUPAC compliant atom nomenclature and 
then change the atom nomenclature in the coordinate file to the IUPAC 
version.

Cheers,
Eldon

**Comment by rhfogh** [comment]
We have asked around, and the end result is that five groups favour changing from IUPAC to PDB_REMED (Eldon, David Case, Charles Schwieters, Peter Guntert - and ultimately ourselves as well), with nobody opposed.  I shall accordingly close this issue and upgrade to version 1.1 soonest, incorporating this change.
